[[libnl]]
arch = "aarch64"
git-tree-sha1 = "516b58695412ac4ec2fb1b62a6fe08a080b4f9e4"
libc = "glibc"
os = "linux"

    [[libnl.download]]
    sha256 = "c8339e6aa9510765d11c58db93067df5b8092c3b57ff0b54c2d3147ac65dfcac"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.aarch64-linux-gnu.tar.gz"
[[libnl]]
arch = "aarch64"
git-tree-sha1 = "72e0558d05cce2259e968ece9851e4b19ecd7e95"
libc = "musl"
os = "linux"

    [[libnl.download]]
    sha256 = "cf6d16637f0c5564b00aa6ad9a6d29a05a9bf1510f6475ccfe90fb64196681af"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.aarch64-linux-musl.tar.gz"
[[libnl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f592815be07b059a72b473687a8e3e31267b3791"
libc = "glibc"
os = "linux"

    [[libnl.download]]
    sha256 = "be7467687968113ab5194713b2afc96a19852759015ae2abf60a5c148fb4e3f8"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.armv7l-linux-gnueabihf.tar.gz"
[[libnl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67b90aa9948e8fd6a434f25438b294a49aa321b0"
libc = "musl"
os = "linux"

    [[libnl.download]]
    sha256 = "4a27c34968932762ca144292817b3a77c659b6b4e5f90c6040bcfd70c3669d5b"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.armv7l-linux-musleabihf.tar.gz"
[[libnl]]
arch = "i686"
git-tree-sha1 = "82985fce463c9c46a943d7fefbb875e6d10f404f"
libc = "glibc"
os = "linux"

    [[libnl.download]]
    sha256 = "f6953e62f880a499c8af7566b2b983b9d046e6ee4e1f15d3a31f8de13022be33"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.i686-linux-gnu.tar.gz"
[[libnl]]
arch = "i686"
git-tree-sha1 = "9bc016b4661c72b2382686c7ac17cb8d5a8e80f0"
libc = "musl"
os = "linux"

    [[libnl.download]]
    sha256 = "29cb1166294ef4abb8da197fe5823d6952f0bf22df6f7141321aa7f222eb0e55"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.i686-linux-musl.tar.gz"
[[libnl]]
arch = "powerpc64le"
git-tree-sha1 = "503962fb7f1354de75bed1636b6bf841db765b0c"
libc = "glibc"
os = "linux"

    [[libnl.download]]
    sha256 = "e54bedd7415a07a13a749060de75b9066e8237dacd672664b8b606b40ca21faf"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.powerpc64le-linux-gnu.tar.gz"
[[libnl]]
arch = "x86_64"
git-tree-sha1 = "dac6dfb429338a4046de9b05e9582a1e33e963a2"
libc = "glibc"
os = "linux"

    [[libnl.download]]
    sha256 = "de9c5d08323e35dd38b4205fefc4b88198324c19b5d2bb119add1b50e6cec609"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.x86_64-linux-gnu.tar.gz"
[[libnl]]
arch = "x86_64"
git-tree-sha1 = "c14784ea3df7ba8d782f70a6ac9b6ade71bf2ec2"
libc = "musl"
os = "linux"

    [[libnl.download]]
    sha256 = "988409749317b0b5ed62e561058cb1bbb719f8f7a86714ab41ed68bcddb087cc"
    url = "https://github.com/JuliaBinaryWrappers/libnl_jll.jl/releases/download/libnl-v3.5.0+1/libnl.v3.5.0.x86_64-linux-musl.tar.gz"
